server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mismanc/ms-config-repo
          clone-on-start: true
  application:
    name: ms-config-server
logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug
